openapi: 3.0.3
info:
  title: OAuth 2.0 Authentication API
  version: 1.0.0
  description: API for user signup and login using OAuth 2.0 password grant.

servers:
  - url: http://localhost:8080

paths:
  /signup:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input
        '409':
          description: User already exists

  /oauth/token:
    post:
      summary: Obtain OAuth 2.0 access token (login)
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                  enum: [password]
                  description: Must be "password"
                username:
                  type: string
                password:
                  type: string
              required:
                - grant_type
                - username
                - password
      responses:
        '200':
          description: OAuth 2.0 token returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '400':
          description: Invalid input or credentials

components:
  schemas:
    Credentials:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    TokenResponse:
      type: object
      properties:
        access_token:
          type: string
        token_type:
          type: string
          example: bearer
        expires_in:
          type: integer
      required:
        - access_token
        - token_type
        - expires_in

  securitySchemes:
    oauth2Password:
      type: oauth2
      flows:
        password: